import type { NextPage } from 'next'
import Head from 'next/head'
import { prisma } from '../db/client'

const Home: NextPage = (props: any) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-2xl font-bold">
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p>
          {props.data}
        </p>
        
      </main>
    </div>
  )
}

export const getServerSideProps = async () => {
  const data = await prisma.newModel.findMany();

  return {
    props: {
      data: JSON.stringify(data)
    }
  }
}
export default Home
